window.MapConstants = {
    continentNames:{
        '002': 'Africa',
        '019': 'Americas',
        '142': 'Asia',
        '150': 'Europe',
        '009': 'Oceania'
    },
    countryNames:{
        'AF': 'Afghanistan',
        'AL': 'Albania',
        'DZ': 'Algeria',
        'AS': 'American Samoa',
        'AD': 'Andorra',
        'AO': 'Angola',
        'AI': 'Anguilla',
        'AQ': 'Antarctica',
        'AG': 'Antigua and Barbuda',
        'AR': 'Argentina',
        'AM': 'Armenia',
        'AW': 'Aruba',
        'AU': 'Australia',
        'AT': 'Austria',
        'AZ': 'Azerbaijan',
        'BS': 'Bahamas',
        'BH': 'Bahrain',
        'BD': 'Bangladesh',
        'BB': 'Barbados',
        'BY': 'Belarus',
        'BE': 'Belgium',
        'BZ': 'Belize',
        'BJ': 'Benin',
        'BM': 'Bermuda',
        'BT': 'Bhutan',
        'BO': 'Bolivia',
        'BA': 'Bosnia and Herzegovina',
        'BW': 'Botswana',
        'BR': 'Brazil',
        'IO': 'British Indian Ocean Territory',
        'BN': 'Brunei Darussalam',
        'BG': 'Bulgaria',
        'BF': 'Burkina Faso',
        'BI': 'Burundi',
        'KH': 'Cambodia',
        'CM': 'Cameroon',
        'CA': 'Canada',
        'CV': 'Cape Verde',
        'KY': 'Cayman Islands',
        'CF': 'Central African Republic',
        'TD': 'Chad',
        'CL': 'Chile',
        'CN': 'China',
        'CX': 'Christmas Island',
        'CC': 'Cocos (Keeling) Islands',
        'CO': 'Colombia',
        'KM': 'Comoros',
        'CG': 'Congo',
        'CD': 'Congo, Democratic Republic',
        'CK': 'Cook Islands',
        'CR': 'Costa Rica',
        'CI': "C涔坱e d'Ivoire",
        'HR': 'Croatia',
        'CU': 'Cuba',
        'CY': 'Cyprus',
        'CZ': 'Czech Republic',
        'DK': 'Denmark',
        'DJ': 'Djibouti',
        'DM': 'Dominica',
        'DO': 'Dominican Republic',
        'EC': 'Ecuador',
        'EG': 'Egypt',
        'SV': 'El Salvador',
        'GQ': 'Equatorial Guinea',
        'ER': 'Eritrea',
        'EE': 'Estonia',
        'ET': 'Ethiopia',
        'FK': 'Falkland Islands',
        'FO': 'Faroe Islands',
        'FJ': 'Fiji',
        'FI': 'Finland',
        'FR': 'France',
        'GF': 'French Guiana',
        'PF': 'French Polynesia',
        'GA': 'Gabon',
        'GM': 'Gambia',
        'GE': 'Georgia',
        'DE': 'Germany',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GR': 'Greece',
        'GL': 'Greenland',
        'GD': 'Grenada',
        'GP': 'Guadeloupe',
        'GU': 'Guam',
        'GT': 'Guatemala',
        'GG': 'Guernsey',
        'GN': 'Guinea',
        'GW': 'Guinea-Bissau',
        'GY': 'Guyana',
        'HT': 'Haiti',
        'VA': 'Holy See (Vatican City State)',
        'HN': 'Honduras',
        'HK': 'Hong Kong',
        'HU': 'Hungary',
        'IS': 'Iceland',
        'IN': 'India',
        'ID': 'Indonesia',
        'IR': 'Iran',
        'IQ': 'Iraq',
        'IE': 'Ireland',
        'IM': 'Isle of Man',
        'IL': 'Israel',
        'IT': 'Italy',
        'JM': 'Jamaica',
        'JP': 'Japan',
        'JE': 'Jersey',
        'JO': 'Jordan',
        'KZ': 'Kazakhstan',
        'KE': 'Kenya',
        'KI': 'Kiribati',
        'KR': 'South Korea',
        'KW': 'Kuwait',
        'KG': 'Kyrgyzstan',
        'LA': 'Laos',
        'LV': 'Latvia',
        'LB': 'Lebanon',
        'LS': 'Lesotho',
        'LR': 'Liberia',
        'LY': 'Libya',
        'LI': 'Liechtenstein',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'MO': 'Macao',
        'MK': 'North Macedonia',
        'MG': 'Madagascar',
        'MW': 'Malawi',
        'MY': 'Malaysia',
        'MV': 'Maldives',
        'ML': 'Mali',
        'MT': 'Malta',
        'MH': 'Marshall Islands',
        'MQ': 'Martinique',
        'MR': 'Mauritania',
        'MU': 'Mauritius',
        'YT': 'Mayotte',
        'MX': 'Mexico',
        'FM': 'Micronesia',
        'MD': 'Moldova',
        'MC': 'Monaco',
        'MN': 'Mongolia',
        'ME': 'Montenegro',
        'MS': 'Montserrat',
        'MA': 'Morocco',
        'MZ': 'Mozambique',
        'MM': 'Myanmar',
        'NA': 'Namibia',
        'NR': 'Nauru',
        'NP': 'Nepal',
        'NL': 'Netherlands',
        'NC': 'New Caledonia',
        'NZ': 'New Zealand',
        'NI': 'Nicaragua',
        'NE': 'Niger',
        'NG': 'Nigeria',
        'NU': 'Niue',
        'NF': 'Norfolk Island',
        'MP': 'Northern Mariana Islands',
        'NO': 'Norway',
        'OM': 'Oman',
        'PK': 'Pakistan',
        'PW': 'Palau',
        'PS': 'Palestine',
        'PA': 'Panama',
        'PG': 'Papua New Guinea',
        'PY': 'Paraguay',
        'PE': 'Peru',
        'PH': 'Philippines',
        'PL': 'Poland',
        'PT': 'Portugal',
        'PR': 'Puerto Rico',
        'QA': 'Qatar',
        'RE': 'R鑼卽nion',
        'RO': 'Romania',
        'RU': 'Russia',
        'RW': 'Rwanda',
        'WS': 'Samoa',
        'SM': 'San Marino',
        'ST': 'Sao Tome and Principe',
        'SA': 'Saudi Arabia',
        'SN': 'Senegal',
        'RS': 'Serbia',
        'SC': 'Seychelles',
        'SL': 'Sierra Leone',
        'SG': 'Singapore',
        'SK': 'Slovakia',
        'SI': 'Slovenia',
        'SB': 'Solomon Islands',
        'SO': 'Somalia',
        'ZA': 'South Africa',
        'ES': 'Spain',
        'LK': 'Sri Lanka',
        'SD': 'Sudan',
        'SR': 'Suriname',
        'SE': 'Sweden',
        'CH': 'Switzerland',
        'SY': 'Syria',
        'TW': 'Taiwan',
        'TJ': 'Tajikistan',
        'TZ': 'Tanzania',
        'TH': 'Thailand',
        'TL': 'Timor-Leste',
        'TG': 'Togo',
        'TK': 'Tokelau',
        'TO': 'Tonga',
        'TT': 'Trinidad and Tobago',
        'TN': 'Tunisia',
        'TR': 'Turkey',
        'TM': 'Turkmenistan',
        'TC': 'Turks and Caicos Islands',
        'TV': 'Tuvalu',
        'UG': 'Uganda',
        'UA': 'Ukraine',
        'AE': 'United Arab Emirates',
        'GB': 'United Kingdom',
        'US': 'United States',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistan',
        'VU': 'Vanuatu',
        'VE': 'Venezuela',
        'VN': 'Vietnam',
        'WF': 'Wallis and Futuna',
        'EH': 'Western Sahara',
        'YE': 'Yemen',
        'ZM': 'Zambia',
        'ZW': 'Zimbabwe',
        'Unknown': 'Unknown'
    },
    subRegionNames:{
        'AU-NSW': 'New South Wales, Australia',
        'AU-VIC': 'Victoria, Australia',
        'AU-QLD': 'Queensland, Australia',
        'AU-SA': 'South Australia, Australia',
        'AU-WA': 'Western Australia, Australia',
        'AU-TAS': 'Tasmania, Australia',
        'AU-NT': 'Northern Territory, Australia',
        'AU-ACT': 'Australian Capital Territory, Australia',
    },
    countryToContinent:{
        // Africa
        'DZ': '002', 'AO': '002', 'BJ': '002', 'BW': '002', 'BF': '002', 'BI': '002',
        'CM': '002', 'CV': '002', 'CF': '002', 'TD': '002', 'KM': '002', 'CG': '002',
        'CD': '002', 'CI': '002', 'DJ': '002', 'EG': '002', 'GQ': '002', 'ER': '002',
        'ET': '002', 'GA': '002', 'GM': '002', 'GH': '002', 'GN': '002', 'GW': '002',
        'KE': '002', 'LS': '002', 'LR': '002', 'LY': '002', 'MG': '002', 'MW': '002',
        'ML': '002', 'MR': '002', 'MU': '002', 'YT': '002', 'MA': '002', 'MZ': '002',
        'NA': '002', 'NE': '002', 'NG': '002', 'RE': '002', 'RW': '002', 'SH': '002',
        'ST': '002', 'SN': '002', 'SC': '002', 'SL': '002', 'SO': '002', 'ZA': '002',
        'SS': '002', 'SD': '002', 'SZ': '002', 'TZ': '002', 'TG': '002', 'TN': '002',
        'UG': '002', 'EH': '002', 'ZM': '002', 'ZW': '002',
        // Americas
        'AI': '019', 'AG': '019', 'AR': '019', 'AW': '019', 'BS': '019', 'BB': '019',
        'BZ': '019', 'BM': '019', 'BO': '019', 'BR': '019', 'VG': '019', 'CA': '019',
        'KY': '019', 'CL': '019', 'CO': '019', 'CR': '019', 'CU': '019', 'DM': '019',
        'DO': '019', 'EC': '019', 'SV': '019', 'FK': '019', 'GF': '019', 'GL': '019',
        'GD': '019', 'GP': '019', 'GT': '019', 'GY': '019', 'HT': '019', 'HN': '019',
        'JM': '019', 'MQ': '019', 'MX': '019', 'MS': '019', 'NI': '019', 'PA': '019',
        'PY': '019', 'PE': '019', 'PR': '019', 'BL': '019', 'KN': '019', 'LC': '019',
        'MF': '019', 'PM': '019', 'VC': '019', 'SR': '019', 'TT': '019', 'TC': '019',
        'VI': '019', 'US': '019', 'UY': '019', 'VE': '019',
        // Asia
        'AF': '142', 'AM': '142', 'AZ': '142', 'BH': '142', 'BD': '142', 'BT': '142',
        'BN': '142', 'KH': '142', 'CN': '142', 'CY': '142', 'GE': '142', 'HK': '142',
        'IN': '142', 'ID': '142', 'IR': '142', 'IQ': '142', 'IL': '142', 'JP': '142',
        'JO': '142', 'KZ': '142', 'KP': '142', 'KR': '142', 'KW': '142', 'KG': '142',
        'LA': '142', 'LB': '142', 'MO': '142', 'MY': '142', 'MV': '142', 'MN': '142',
        'MM': '142', 'NP': '142', 'OM': '142', 'PK': '142', 'PS': '142', 'PH': '142',
        'QA': '142', 'SA': '142', 'SG': '142', 'LK': '142', 'SY': '142', 'TW': '142',
        'TJ': '142', 'TH': '142', 'TL': '142', 'TR': '142', 'TM': '142', 'AE': '142',
        'UZ': '142', 'VN': '142', 'YE': '142',
        // Europe
        'AL': '150', 'AD': '150', 'AT': '150', 'BY': '150', 'BE': '150', 'BA': '150',
        'BG': '150', 'HR': '150', 'CZ': '150', 'DK': '150', 'EE': '150', 'FO': '150',
        'FI': '150', 'FR': '150', 'DE': '150', 'GI': '150', 'GR': '150', 'HU': '150',
        'IS': '150', 'IE': '150', 'IT': '150', 'LV': '150', 'LI': '150', 'LT': '150',
        'LU': '150', 'MK': '150', 'MT': '150', 'MD': '150', 'MC': '150', 'ME': '150',
        'NL': '150', 'NO': '150', 'PL': '150', 'PT': '150', 'RO': '150', 'RU': '150',
        'SM': '150', 'RS': '150', 'SK': '150', 'SI': '150', 'ES': '150', 'SE': '150',
        'CH': '150', 'UA': '150', 'GB': '150', 'VA': '150',
        // Oceania
        'AS': '009', 'AU': '009', 'CK': '009', 'FJ': '009', 'PF': '009', 'GU': '009',
        'KI': '009', 'MH': '009', 'FM': '009', 'NR': '009', 'NC': '009', 'NZ': '009',
        'NU': '009', 'NF': '009', 'MP': '009', 'PW': '009', 'PG': '009', 'PN': '009',
        'WS': '009', 'SB': '009', 'TK': '009', 'TO': '009', 'TV': '009', 'VU': '009',
        'WF': '009',
    }
}